window.PLAN_DATA = {
  "version": "2026.08.07-13",
  "semester": {
    "title": "Cronograma · segundo semestre 2026",
    "start": "2026-08-03",
    "end": "2026-11-30"
  },
  "subjects": {
    "fuaa": {
      "name": "Fundamentos de Aprendizaje Automático",
      "short": "FuAA",
      "color": "#8cff3a",
      "status": "Cronograma oficial cargado",
      "source": "FuAA 2026"
    },
    "redes": {
      "name": "Redes de Computadoras",
      "short": "Redes",
      "color": "#36a9ff",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma Redes 2026"
    },
    "fbd": {
      "name": "Fundamentos de Bases de Datos",
      "short": "FBD",
      "color": "#ff9a3c",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma FBD 2026 proporcionado"
    },
    "pln": {
      "name": "Introducción al Procesamiento de Lenguaje Natural",
      "short": "IntroPLN",
      "color": "#ff4fcf",
      "status": "Clases OpenFing cargadas; cronograma pendiente",
      "source": "OpenFing"
    }
  },
  "typeLabels": {
    "openfing": "Clase OpenFing",
    "reading": "Lectura",
    "practical": "Práctico",
    "course-class": "Actividad del curso",
    "discussion": "Discusión",
    "control": "Control",
    "questionnaire": "Cuestionario",
    "workshop": "Taller",
    "partial": "Parcial",
    "partial-window": "Período de parciales",
    "assignment-published": "Publicación de obligatorio",
    "deadline": "Entrega",
    "monitoring": "Monitoreo",
    "defense": "Defensa",
    "holiday": "Feriado",
    "no-class": "Sin clase",
    "consultation": "Consulta",
    "notice": "Pendiente"
  },
  "typeMarks": {
    "openfing": "OF",
    "reading": "LIBRO",
    "practical": "P",
    "course-class": "CLASE",
    "discussion": "DISC",
    "control": "CTRL",
    "questionnaire": "CP",
    "workshop": "TALLER",
    "partial": "PARCIAL",
    "partial-window": "PARCIALES",
    "assignment-published": "OB",
    "deadline": "ENTREGA",
    "monitoring": "LAB",
    "defense": "DEF",
    "holiday": "FERIADO",
    "no-class": "—",
    "consultation": "CONSULTA",
    "notice": "PEND."
  },
  "items": [
    {
      "id": "redes-20260803-01",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Presentación e Introducción",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 0
    },
    {
      "id": "redes-20260803-02",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 1",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 10
    },
    {
      "id": "redes-20260803-03",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 2",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 20
    },
    {
      "id": "redes-20260803-04",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 3",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 30
    },
    {
      "id": "redes-20260803-05",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 1",
      "details": "Lectura asignada para Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 40
    },
    {
      "id": "redes-20260803-06",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P1 · Retardos",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 50
    },
    {
      "id": "redes-20260803-09",
      "week": "2026-08-03",
      "eventDate": "2026-08-07",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Publicación del Obligatorio 1",
      "details": "Plazo indicado: 5 semanas",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 80
    },
    {
      "id": "redes-20260810-01",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 90
    },
    {
      "id": "redes-20260810-02",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 4",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 100
    },
    {
      "id": "redes-20260810-03",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 5",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 110
    },
    {
      "id": "redes-20260810-04",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta 2.3 y sección 2.7",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 120
    },
    {
      "id": "redes-20260810-05",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P1 y P2 · HTTP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 130
    },
    {
      "id": "redes-20260810-08",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 160
    },
    {
      "id": "redes-20260817-01",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 170
    },
    {
      "id": "redes-20260817-02",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 6",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 180
    },
    {
      "id": "redes-20260817-03",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 7",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 190
    },
    {
      "id": "redes-20260817-04",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta el final",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 200
    },
    {
      "id": "redes-20260817-05",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P3 · Sockets",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 210
    },
    {
      "id": "redes-20260817-08",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 240
    },
    {
      "id": "redes-20260824-01",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 250
    },
    {
      "id": "redes-20260824-02",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 6",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 260
    },
    {
      "id": "redes-20260824-03",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 7",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 270
    },
    {
      "id": "redes-20260824-04",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta el final",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 280
    },
    {
      "id": "redes-20260824-05",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P3 y P4 · EMAIL y DNS",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 290
    },
    {
      "id": "redes-20260824-08",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 320
    },
    {
      "id": "redes-20260831-01",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 330
    },
    {
      "id": "redes-20260831-02",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 340
    },
    {
      "id": "redes-20260831-03",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 350
    },
    {
      "id": "redes-20260831-04",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.4",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 360
    },
    {
      "id": "redes-20260831-05",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P4",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 370
    },
    {
      "id": "redes-20260831-08",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 400
    },
    {
      "id": "redes-20260907-01",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 410
    },
    {
      "id": "redes-20260907-02",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 420
    },
    {
      "id": "redes-20260907-03",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 430
    },
    {
      "id": "redes-20260907-04",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.4",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 440
    },
    {
      "id": "redes-20260907-05",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5 · RDT, control de congestión y TCP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 450
    },
    {
      "id": "redes-20260907-07",
      "week": "2026-09-07",
      "eventDate": "2026-09-11",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 1",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 470
    },
    {
      "id": "redes-20260907-08",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 480
    },
    {
      "id": "redes-20260914-01",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 490
    },
    {
      "id": "redes-20260914-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 10",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 500
    },
    {
      "id": "redes-20260914-03",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 510
    },
    {
      "id": "redes-20260914-04",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.6",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 520
    },
    {
      "id": "redes-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 530
    },
    {
      "id": "redes-20260914-08",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 560
    },
    {
      "id": "redes-20260921-01",
      "week": "2026-09-21",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 570
    },
    {
      "id": "redes-20260928-02",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 590
    },
    {
      "id": "redes-20260928-03",
      "week": "2026-09-28",
      "eventDate": "2026-10-02",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Publicación del Obligatorio 2",
      "details": "Plazo indicado: 6 semanas",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 600
    },
    {
      "id": "redes-20261005-01",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 610
    },
    {
      "id": "redes-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 620
    },
    {
      "id": "redes-20261005-03",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta el final",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 630
    },
    {
      "id": "redes-20261005-04",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5 · RDT, control de congestión y TCP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 640
    },
    {
      "id": "redes-20261005-07",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 670
    },
    {
      "id": "redes-20261012-01",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de datos",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 680
    },
    {
      "id": "redes-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 12",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 690
    },
    {
      "id": "redes-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 13",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 700
    },
    {
      "id": "redes-20261012-04",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 4 hasta 4.3",
      "details": "Lectura asignada para Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 710
    },
    {
      "id": "redes-20261012-05",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6 · Direccionamiento, numeración, forwarding y LPM",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 720
    },
    {
      "id": "redes-20261012-08",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 750
    },
    {
      "id": "redes-20261019-01",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: IPv6",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 760
    },
    {
      "id": "redes-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 770
    },
    {
      "id": "redes-20261019-03",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 18",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 780
    },
    {
      "id": "redes-20261019-04",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 19",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 790
    },
    {
      "id": "redes-20261019-05",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Material IPv6",
      "details": "Lectura asignada para Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 800
    },
    {
      "id": "redes-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 810
    },
    {
      "id": "redes-20261019-09",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 840
    },
    {
      "id": "redes-20261026-01",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de control",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 850
    },
    {
      "id": "redes-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 860
    },
    {
      "id": "redes-20261026-03",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 15",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 870
    },
    {
      "id": "redes-20261026-04",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 5 hasta 5.3",
      "details": "Lectura asignada para Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 880
    },
    {
      "id": "redes-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7 · Enrutamiento (DV y LS), OSPF y BGP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 890
    },
    {
      "id": "redes-20261026-08",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 920
    },
    {
      "id": "redes-20261102-01",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de control",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 930
    },
    {
      "id": "redes-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 16",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 940
    },
    {
      "id": "redes-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 17",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 950
    },
    {
      "id": "redes-20261102-04",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 5 hasta el final; Multicast y Broadcast",
      "details": "Lectura asignada para Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 960
    },
    {
      "id": "redes-20261102-05",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 970
    },
    {
      "id": "redes-20261102-08",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1000
    },
    {
      "id": "redes-20261109-01",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Enlace",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1010
    },
    {
      "id": "redes-20261109-02",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 20",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1020
    },
    {
      "id": "redes-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 21",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1030
    },
    {
      "id": "redes-20261109-04",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 6 hasta 6.3",
      "details": "Lectura asignada para Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1040
    },
    {
      "id": "redes-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P8 y P9 · Capa de enlace",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1050
    },
    {
      "id": "redes-20261109-08",
      "week": "2026-11-09",
      "eventDate": "2026-11-13",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 2",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1080
    },
    {
      "id": "redes-20261109-09",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1090
    },
    {
      "id": "redes-20261116-01",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Enlace",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1100
    },
    {
      "id": "redes-20261116-02",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 22",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1110
    },
    {
      "id": "redes-20261116-03",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 23",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1120
    },
    {
      "id": "redes-20261116-04",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 6 hasta el final",
      "details": "Lectura asignada para Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1130
    },
    {
      "id": "redes-20261116-05",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P9",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1140
    },
    {
      "id": "redes-20261116-08",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1170
    },
    {
      "id": "redes-20261123-01",
      "week": "2026-11-23",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1180
    },
    {
      "id": "redes-20261130-01",
      "week": "2026-11-30",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1190
    },
    {
      "id": "fuaa-20260810-01",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 1 · Introducción al problema de aprendizaje",
      "details": "Tema 1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1200
    },
    {
      "id": "fuaa-20260810-02",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 2 · El problema de aprendizaje",
      "details": "Tema 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1210
    },
    {
      "id": "fuaa-20260810-03",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 1: 1.1, 1.2 · Tema 2: 1.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1220
    },
    {
      "id": "fuaa-20260817-01",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 4 · El modelo lineal",
      "details": "Tema 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1230
    },
    {
      "id": "fuaa-20260817-02",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 5 · Error y ruido",
      "details": "Tema 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1240
    },
    {
      "id": "fuaa-20260817-03",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 3: 3.1, 3.2, 3.4 · Tema 4: 1.4, 1.3.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1250
    },
    {
      "id": "fuaa-20260824-01",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 6 · Entrenamiento versus prueba",
      "details": "Tema 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1260
    },
    {
      "id": "fuaa-20260824-02",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 8 · Teoría de la generalización",
      "details": "Tema 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1270
    },
    {
      "id": "fuaa-20260824-03",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 5: 2.1, 2.1.1 · Tema 6: 2.1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1280
    },
    {
      "id": "fuaa-20260831-01",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 9 · La dimensión VC",
      "details": "Tema 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1290
    },
    {
      "id": "fuaa-20260831-02",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 10 · Compromiso sesgo-varianza",
      "details": "Tema 8",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1300
    },
    {
      "id": "fuaa-20260831-03",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 7: 2.2 · Tema 8: 2.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1310
    },
    {
      "id": "fuaa-20260907-01",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 12 · El modelo lineal II",
      "details": "Tema 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1320
    },
    {
      "id": "fuaa-20260907-02",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 13 · Sobreajuste",
      "details": "Tema 10",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1330
    },
    {
      "id": "fuaa-20260907-03",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 14 · Regularización",
      "details": "Tema 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1340
    },
    {
      "id": "fuaa-20260907-04",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 9: 3.3 · Tema 10: 4.1 · Tema 11: 4.2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1350
    },
    {
      "id": "fuaa-20260914-01",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 16 · Validación",
      "details": "Tema 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1360
    },
    {
      "id": "fuaa-20260914-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 12: 4.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1370
    },
    {
      "id": "fuaa-20261005-01",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 17 · Epílogo de los fundamentos teóricos",
      "details": "Tema 13",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1380
    },
    {
      "id": "fuaa-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 18 · Perceptrón multicapa",
      "details": "Tema 14",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1390
    },
    {
      "id": "fuaa-20261005-03",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 19 · Redes neuronales",
      "details": "Tema 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1400
    },
    {
      "id": "fuaa-20261005-04",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 13: 5.1, 5.2, 5.3 · Tema 14: 7.1, 7.2 · Tema 15: 7.3, 7.4, 7.5, 7.6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1410
    },
    {
      "id": "fuaa-20261019-01",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 22 · Máquinas de vectores de soporte",
      "details": "Tema 16",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1420
    },
    {
      "id": "fuaa-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 23 · Métodos de Kernel",
      "details": "Tema 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1430
    },
    {
      "id": "fuaa-20261019-03",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 16: 8.1, 8.2 · Tema 17: 8.3, 8.4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1440
    },
    {
      "id": "fuaa-20261026-01",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 25 · Métodos basados en similitud",
      "details": "Tema 18",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1450
    },
    {
      "id": "fuaa-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 26 · Aprendizaje no supervisado",
      "details": "Tema 19",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1460
    },
    {
      "id": "fuaa-20261026-03",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 18: 6.1, 6.2, 6.3 · Tema 19: 6.3, 6.4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1470
    },
    {
      "id": "fuaa-20261109-01",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 28 · Ingeniería de características",
      "details": "Tema 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1480
    },
    {
      "id": "fuaa-20260803-02",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "fuaa",
      "type": "workshop",
      "title": "Consultas / Taller",
      "details": "P0, Python y NumPy",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1500
    },
    {
      "id": "fuaa-20260810-05",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 0",
      "details": "Temas 1 y 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1520
    },
    {
      "id": "fuaa-20260810-06",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 1",
      "details": "Temas 1 y 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1530
    },
    {
      "id": "fuaa-20260810-07",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP01",
      "details": "Vinculado al Práctico 1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1540
    },
    {
      "id": "fuaa-20260817-05",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 1",
      "details": "Temas 1, 2 y 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1560
    },
    {
      "id": "fuaa-20260817-06",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1570
    },
    {
      "id": "fuaa-20260817-07",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP02",
      "details": "Vinculado al Práctico 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1580
    },
    {
      "id": "fuaa-20260824-05",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1600
    },
    {
      "id": "fuaa-20260824-06",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP03",
      "details": "Vinculado al Práctico 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1610
    },
    {
      "id": "fuaa-20260831-05",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 2",
      "details": "Temas 4, 5, 6 y 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1630
    },
    {
      "id": "fuaa-20260831-06",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3",
      "details": "Temas 6, 7, 8 y 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1640
    },
    {
      "id": "fuaa-20260831-07",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP04",
      "details": "Vinculado al Práctico 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1650
    },
    {
      "id": "fuaa-20260907-06",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3 / Práctico 4",
      "details": "Temas 6, 7, 8 y 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1670
    },
    {
      "id": "fuaa-20260907-07",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP05",
      "details": "Vinculado a los prácticos",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1680
    },
    {
      "id": "fuaa-20260914-04",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 3",
      "details": "Temas 8, 9, 10 y 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1700
    },
    {
      "id": "fuaa-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 4",
      "details": "Temas 10, 11 y 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1710
    },
    {
      "id": "fuaa-20260914-06",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP06",
      "details": "Vinculado al Práctico 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1720
    },
    {
      "id": "fuaa-20260921-02",
      "week": "2026-09-21",
      "eventDate": "2026-09-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Primer parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1740
    },
    {
      "id": "fuaa-20260928-01",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1750
    },
    {
      "id": "fuaa-20261005-06",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5 / scikit-learn",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1770
    },
    {
      "id": "fuaa-20261005-07",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP07",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1780
    },
    {
      "id": "fuaa-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1800
    },
    {
      "id": "fuaa-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP08",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1810
    },
    {
      "id": "fuaa-20261019-05",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 4",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1830
    },
    {
      "id": "fuaa-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1840
    },
    {
      "id": "fuaa-20261019-07",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP09",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1850
    },
    {
      "id": "fuaa-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 5",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1870
    },
    {
      "id": "fuaa-20261026-06",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1880
    },
    {
      "id": "fuaa-20261026-07",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP10",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1890
    },
    {
      "id": "fuaa-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1910
    },
    {
      "id": "fuaa-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP11",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1920
    },
    {
      "id": "fuaa-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1940
    },
    {
      "id": "fuaa-20261109-04",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 6",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1950
    },
    {
      "id": "fuaa-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP12",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1960
    },
    {
      "id": "fuaa-20261123-01",
      "week": "2026-11-23",
      "eventDate": "2026-11-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Segundo parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1990
    },
    {
      "id": "fuaa-20261123-02",
      "week": "2026-11-23",
      "eventDate": "",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2000
    },
    {
      "id": "fbd-20260803-01",
      "week": "2026-08-03",
      "periodLabel": "Semana 1 · 03/08–09/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Introducción",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2010
    },
    {
      "id": "fbd-20260803-02",
      "week": "2026-08-03",
      "periodLabel": "Semana 1 · 03/08–09/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Conceptual",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2020
    },
    {
      "id": "fbd-20260803-03",
      "week": "2026-08-03",
      "periodLabel": "Semana 1 · 03/08–09/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 1",
      "details": "Desde el minuto 16:43",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2030
    },
    {
      "id": "fbd-20260803-04",
      "week": "2026-08-03",
      "periodLabel": "Semana 1 · 03/08–09/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 2",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2040
    },
    {
      "id": "fbd-20260810-01",
      "week": "2026-08-10",
      "periodLabel": "Semana 2 · 10/08–16/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Conceptual",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2060
    },
    {
      "id": "fbd-20260810-02",
      "week": "2026-08-10",
      "periodLabel": "Semana 2 · 10/08–16/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Modelo Relacional",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2070
    },
    {
      "id": "fbd-20260810-03",
      "week": "2026-08-10",
      "periodLabel": "Semana 2 · 10/08–16/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 3",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2080
    },
    {
      "id": "fbd-20260810-04",
      "week": "2026-08-10",
      "periodLabel": "Semana 2 · 10/08–16/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 4",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2090
    },
    {
      "id": "fbd-20260810-05",
      "week": "2026-08-10",
      "periodLabel": "Semana 2 · 10/08–16/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 1 · Modelo Entidad Relación",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2100
    },
    {
      "id": "fbd-20260817-01",
      "week": "2026-08-17",
      "periodLabel": "Semana 3 · 17/08–23/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Álgebra Relacional",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2110
    },
    {
      "id": "fbd-20260817-02",
      "week": "2026-08-17",
      "periodLabel": "Semana 3 · 17/08–23/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 5",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2120
    },
    {
      "id": "fbd-20260817-03",
      "week": "2026-08-17",
      "periodLabel": "Semana 3 · 17/08–23/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 6",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2130
    },
    {
      "id": "fbd-20260817-04",
      "week": "2026-08-17",
      "periodLabel": "Semana 3 · 17/08–23/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 1 · Modelo Entidad Relación",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2140
    },
    {
      "id": "fbd-20260824-01",
      "week": "2026-08-24",
      "periodLabel": "Semana 4 · 24/08–30/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Lenguajes de Consulta · Cálculo Relacional",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2150
    },
    {
      "id": "fbd-20260824-02",
      "week": "2026-08-24",
      "periodLabel": "Semana 4 · 24/08–30/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 7",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2160
    },
    {
      "id": "fbd-20260824-03",
      "week": "2026-08-24",
      "periodLabel": "Semana 4 · 24/08–30/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 8",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2170
    },
    {
      "id": "fbd-20260824-04",
      "week": "2026-08-24",
      "periodLabel": "Semana 4 · 24/08–30/08",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 2 · Álgebra Relacional",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2180
    },
    {
      "id": "fbd-20260831-01",
      "week": "2026-08-31",
      "periodLabel": "Semana 5 · 31/08–06/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Lenguaje SQL",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2190
    },
    {
      "id": "fbd-20260831-02",
      "week": "2026-08-31",
      "periodLabel": "Semana 5 · 31/08–06/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 9",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2200
    },
    {
      "id": "fbd-20260831-03",
      "week": "2026-08-31",
      "periodLabel": "Semana 5 · 31/08–06/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 10",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2210
    },
    {
      "id": "fbd-20260831-04",
      "week": "2026-08-31",
      "periodLabel": "Semana 5 · 31/08–06/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 3 · Cálculo Relacional",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2220
    },
    {
      "id": "fbd-20260907-01",
      "week": "2026-09-07",
      "periodLabel": "Semana 6 · 07/09–13/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional · Dependencias Funcionales",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2230
    },
    {
      "id": "fbd-20260907-02",
      "week": "2026-09-07",
      "periodLabel": "Semana 6 · 07/09–13/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 11",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2240
    },
    {
      "id": "fbd-20260907-03",
      "week": "2026-09-07",
      "periodLabel": "Semana 6 · 07/09–13/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 12",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2250
    },
    {
      "id": "fbd-20260907-04",
      "week": "2026-09-07",
      "periodLabel": "Semana 6 · 07/09–13/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 4 · SQL",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2260
    },
    {
      "id": "fbd-20260914-01",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional · Normalización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2270
    },
    {
      "id": "fbd-20260914-02",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 13",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2280
    },
    {
      "id": "fbd-20260914-03",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 14",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2290
    },
    {
      "id": "fbd-20260914-04",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Prácticos 2, 3 y 4",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2300
    },
    {
      "id": "fbd-20260921-01",
      "week": "2026-09-21",
      "periodLabel": "Semanas 8 y 9 · 19/09–03/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "partial-window",
      "title": "Parciales",
      "details": "Período indicado para las semanas 8 y 9.",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2310
    },
    {
      "id": "fbd-20261005-01",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional · Normalización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2320
    },
    {
      "id": "fbd-20261005-02",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 13",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2330
    },
    {
      "id": "fbd-20261005-03",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 14",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2340
    },
    {
      "id": "fbd-20261005-04",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 5 · Dependencias funcionales",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2350
    },
    {
      "id": "fbd-20261012-01",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional (DMVs)",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2360
    },
    {
      "id": "fbd-20261012-02",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Pasaje de MER a MR",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2370
    },
    {
      "id": "fbd-20261012-03",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 15",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2380
    },
    {
      "id": "fbd-20261012-04",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 16",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2390
    },
    {
      "id": "fbd-20261012-05",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 6 · Normalización",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2400
    },
    {
      "id": "fbd-20261019-01",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Estrategia de acceso a datos",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2410
    },
    {
      "id": "fbd-20261019-02",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 17",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2420
    },
    {
      "id": "fbd-20261019-03",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 7 · Dependencias Multivaluadas",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2430
    },
    {
      "id": "fbd-20261026-01",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Optimización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2440
    },
    {
      "id": "fbd-20261026-02",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 18",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2450
    },
    {
      "id": "fbd-20261026-03",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 19",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2460
    },
    {
      "id": "fbd-20261026-04",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 8 · Pasaje de MER a MR",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2470
    },
    {
      "id": "fbd-20261102-01",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Concurrencia",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2480
    },
    {
      "id": "fbd-20261102-02",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Recuperación",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2490
    },
    {
      "id": "fbd-20261102-03",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 20",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2500
    },
    {
      "id": "fbd-20261102-04",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 21",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2510
    },
    {
      "id": "fbd-20261102-05",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 9 · Optimización",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2520
    },
    {
      "id": "fbd-20261109-01",
      "week": "2026-11-09",
      "periodLabel": "Semana 15 · 09/11–15/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Repaso",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2530
    },
    {
      "id": "fbd-20261109-02",
      "week": "2026-11-09",
      "periodLabel": "Semana 15 · 09/11–15/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 10 · Concurrencia y Recuperación",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2540
    },
    {
      "id": "pln-openfing-01",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 1 · Introducción al Procesamiento de Lenguaje Natural",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2560
    },
    {
      "id": "pln-openfing-02",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 2 · Introducción a la Gramática del Español",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2570
    },
    {
      "id": "pln-openfing-03",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 3 · Introducción a la Gramática del Español",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2580
    },
    {
      "id": "pln-openfing-04",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 4 · Expresiones Regulares y Normalización de Textos",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2590
    },
    {
      "id": "pln-openfing-05",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 5 · Distancia de Mínima Edición. Transductores. Morfología",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2600
    },
    {
      "id": "pln-openfing-06",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 6 · Morfología de Estado Finito. Modelo del Canal Ruidoso para Detección de Errores",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2610
    },
    {
      "id": "pln-openfing-07",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 7 · Modelos de Lenguaje",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2620
    },
    {
      "id": "pln-openfing-08",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 8 · Análisis Léxico y Hidden Markov Models",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2630
    },
    {
      "id": "pln-openfing-09",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 9 · Clasificación",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2640
    },
    {
      "id": "pln-openfing-10",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 10 · Métodos de Clasificación Supervisada",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2650
    },
    {
      "id": "pln-openfing-11",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 11 · Sintaxis",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2660
    },
    {
      "id": "pln-openfing-12",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 12 · Análisis Sintáctico",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2670
    },
    {
      "id": "pln-openfing-13",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 13 · Semántica",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2680
    },
    {
      "id": "pln-openfing-14",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 14 · Semántica Léxica. Roles Semánticos",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2690
    },
    {
      "id": "pln-openfing-15",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 15 · Redes Neuronales y Vectores de Palabras",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2700
    },
    {
      "id": "pln-openfing-16",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 16 · Análisis de Subjetividad",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2710
    },
    {
      "id": "pln-openfing-17",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 17 · Clustering. Modelado de Tópicos",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2720
    },
    {
      "id": "pln-openfing-18",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 18 · Traducción Automática (I)",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2730
    },
    {
      "id": "pln-openfing-19",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 19 · Traducción Automática (II)",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2740
    },
    {
      "id": "pln-openfing-20",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "openfing",
      "title": "Clase OpenFing 20 · Recuperación de Información",
      "details": "",
      "source": "OpenFing",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2750
    }
  ]
};
